[2024-04-04T23:57:41.504+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_postgre_operator.insert_data_task manual__2024-04-04T23:57:36.152730+00:00 [queued]>
[2024-04-04T23:57:41.511+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_postgre_operator.insert_data_task manual__2024-04-04T23:57:36.152730+00:00 [queued]>
[2024-04-04T23:57:41.512+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-04T23:57:41.523+0000] {taskinstance.py:2217} INFO - Executing <Task(PostgresBulkLoadOperator): insert_data_task> on 2024-04-04 23:57:36.152730+00:00
[2024-04-04T23:57:41.527+0000] {standard_task_runner.py:60} INFO - Started process 1253 to run task
[2024-04-04T23:57:41.529+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_postgre_operator', 'insert_data_task', 'manual__2024-04-04T23:57:36.152730+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/dag_python_operator_extract.py', '--cfg-path', '/tmp/tmpxzblq3ad']
[2024-04-04T23:57:41.531+0000] {standard_task_runner.py:88} INFO - Job 109: Subtask insert_data_task
[2024-04-04T23:57:41.578+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_postgre_operator.insert_data_task manual__2024-04-04T23:57:36.152730+00:00 [running]> on host 7f6ff1f67725
[2024-04-04T23:57:41.686+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_postgre_operator' AIRFLOW_CTX_TASK_ID='insert_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-04-04T23:57:36.152730+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-04T23:57:36.152730+00:00'
[2024-04-04T23:57:41.688+0000] {dag_python_operator_extract.py:89} ERROR - File 'None' not found.
[2024-04-04T23:57:41.689+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/opt/airflow/dags/dag_python_operator_extract.py", line 84, in execute
    with open(self.file_path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'None'
[2024-04-04T23:57:41.706+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=dag_postgre_operator, task_id=insert_data_task, execution_date=20240404T235736, start_date=20240404T235741, end_date=20240404T235741
[2024-04-04T23:57:41.719+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 109 for task insert_data_task ([Errno 2] No such file or directory: 'None'; 1253)
[2024-04-04T23:57:41.742+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-04T23:57:41.758+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/models/baseoperator.py:1201 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-04-04T23:57:41.772+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
